config/routes.rb
Rails.application.routes.draw do

  root 'circonscriptions#index'
  get 'panneaus/get_nearest_pannel' =>  'panneaus#get_nearest_pannel'
  get "panneaus/:id/edit_state" => 'panneaus#edit_state', as: :edit_state_panneau_path
  get "panneaus/secret_geo_json_loading" => 'panneaus#secret_geo_json_loading'
  get "google_map" => 'panneaus#google_map', as: :google_map_path
  get "open_street_amp" => 'panneaus#open_street_map', as: :open_street_map_path
  get "panneaus/get_kml" => "panneaus#get_kml"
  get "panneaus_gm" => 'panneaus#google_map'

  resources :panneaus

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/panneau.rb
class Panneau < ApplicationRecord
	scope :ville, -> (ville) { where ville: ville }

end

app/controllers/panneaus_controller.rb
class PanneausController < ApplicationController
  before_action :set_panneau, only: [:show, :edit,:edit_state, :update, :destroy]
  before_action :set_panneaus, only: [:index, :get_nearest_pannel, :open_street_map, :google_map, :get_kml]
  
  # GET /panneaus
  # GET /panneaus.json
  def index
    lat = params[:lat]
    long = params[:long]
    is_ok = params[:is_ok]
    id_panneaux = params[:id_panneaux] 
    if params[:editable]
      @editable = true
    end
  end

  def open_street_map
    lat = params[:lat]
    long = params[:long]
    is_ok = params[:is_ok]
    id_panneaux = params[:id_panneaux] 
  end

  def google_map
    lat = params[:lat]
    long = params[:long]
    is_ok = params[:is_ok]
    id_panneaux = params[:id_panneaux] 
  end

  # GET /panneaus/1
  # GET /panneaus/1.json
  def show
  end

  # GET /panneaus/new
  def new
    @villes = Panneau.select(:ville).map(&:ville).uniq
    @panneau = Panneau.new
    if params[:ville]
      @panneau.ville = params[:ville]
    end
  end

  # GET /panneaus/1/edit
  def edit
    @villes = Panneau.select(:ville).map(&:ville).uniq
  end

  def edit_state
  end

  # POST /panneaus
  # POST /panneaus.json
  def create
    @panneau = Panneau.new(panneau_params)

    respond_to do |format|
      if @panneau.save
        format.html { redirect_to "/panneaus?editable=true&ville=#{@panneau.ville}", notice: 'Panneau was successfully created.' }
        format.json { render :show, status: :created, location: @panneau }
      else
        format.html { render :new }
        format.json { render json: @panneau.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panneaus/1.json
  def update

    respond_to do |format|
      if @panneau.update(panneau_params)

        format.html { redirect_to "/panneaus?editable=true&ville=#{@panneau.ville}" , notice: 'Panneau was successfully updated.' }
        format.json { render :show, status: :ok, location: @panneau }
      else
        format.html { render :edit }
        format.json { render json: @panneau.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /panneaus/1
  # DELETE /panneaus/1.json
  def destroy
    ville = @panneau.ville.to_s
    @panneau.destroy
    respond_to do |format|
      format.html { redirect_to panneaus_url(:ville=>ville,:editable=>true), notice: 'Panneau was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_nearest_pannel

    lat = params[:lat]
    long = params[:long]
    is_ok = params[:is_ok]
    id_panneaux = params[:id_panneaux]

    if id_panneaux && is_ok

      @panneau = @panneaus.find(id_panneaux.to_i)
      if is_ok != "false" && is_ok != false

        @panneau.update(:is_ok=> true)
      else

        @panneau.update(:is_ok=> false)
      end
    end

    if lat && long && @panneaus
      panneaux_sorted = @panneaus.sort_by{|panneau| 
        getDistanceFromLatLonInKm(panneau[:long].to_f,panneau[:lat].to_f,lat.to_f,long.to_f)
      }
      render json: panneaux_sorted.to_json
    else
      render json: {:result=>200}.to_json
    end

  end

  def getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) 

      p = 0.017453292519943295 #Math.PI / 180
      a = 0.5 - Math::cos((lat2 - lat1) * p)/2 + Math::cos(lat1 * p) * Math::cos(lat2 * p) * (1 - Math::cos((lon2 - lon1) * p))/2;
      dist = 12742 * Math.asin(Math.sqrt(a))
      return dist # 2 * R; R = 6371 km

    end

  def deg2rad(deg)
    return deg * (Math::PI/180)
  end
  
  def secret_geo_json_loading
    #patch for adding marseille 4 ieme circo
    extension = "geojson"
    actualFolder = File.dirname(__FILE__)
    all_geojson_filter = "#{actualFolder}/../../db/circo/*.#{extension}"
    all_json_files = Dir.glob(all_geojson_filter)

    all_json_files.each{|geo_json_path|

      geo_jsons = getHashFromJsonFile geo_json_path

      ville = File.basename(geo_json_path, ".#{extension}")

      geo_json_features = geo_jsons[:features]

      panneaux_mavoix = geo_json_features.map{|geojson| 
        if geojson[:geometry]
          if geojson[:geometry][:coordinates]
            if geojson[:properties]
              if geojson[:properties][:description]
                {:lat => geojson[:geometry][:coordinates][0], :long =>geojson[:geometry][:coordinates][1], :name => geojson[:properties][:description], :is_ok=> false, :ville=>ville}
              elsif geojson[:properties][:Description]
                {:lat => geojson[:geometry][:coordinates][0], :long =>geojson[:geometry][:coordinates][1], :name => geojson[:properties][:Description], :is_ok=> false, :ville=>ville}
              elsif geojson[:properties][:Nom]
                {:lat => geojson[:geometry][:coordinates][0], :long =>geojson[:geometry][:coordinates][1], :name => geojson[:properties][:Nom], :is_ok=> false, :ville=>ville}
              elsif geojson[:properties][:Name]
                {:lat => geojson[:geometry][:coordinates][0], :long =>geojson[:geometry][:coordinates][1], :name => geojson[:properties][:Name], :is_ok=> false, :ville=>ville}
              else
                {:lat => geojson[:geometry][:coordinates][0], :long =>geojson[:geometry][:coordinates][1], :name => "voir sur la carte", :is_ok=> false, :ville=>ville}
              end
            else
              puts "no geojson[:properties]"
            end
          else
            puts "no geojson[:geometry][:coordinates] "
          end
        else
          puts "no geojson[:geometry]"
        end
      }
      puts panneaux_mavoix.inspect
      panneaux_mavoix = panneaux_mavoix.select{|pnx| pnx != nil}
      panneaux_mavoix.uniq!
      panneaux_mavoix.each{|panneau|
        existing_panneau = Panneau.where(:ville => panneau[:ville]).where(:name => panneau[:name]).where(:long => panneau[:long])

        if existing_panneau == []
          Panneau.create(panneau)
        else 
          puts "non #{existing_panneau.to_json}"
        end
      }
    } 
    redirect_to panneaus_url, notice: 'Panneau ajouté.'
  end


  def get_kml

    xml = Builder::XmlMarkup.new
    render 'panneaus/get_kml.xml.builder', formats: [:xml]
    
  end

end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_panneau
    @panneau = Panneau.find(params[:id])
  end

  def set_panneaus
    #puts "----set panneau --#{params[:ville]}--"
    @panneaus = Panneau.all
    if params[:ville]
      if params[:ville] == "Paris"
        @panneaus = @panneaus.where("ville like ?", "%Paris%")
      else
        @panneaus = @panneaus.ville(params[:ville]) if params[:ville]
      end
    end
    @panneaus = @panneaus.order(:name)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def panneau_params
    params.require(:panneau).permit(:lat, :long, :name, :is_ok, :ville)
  end

  def getHashFromJsonFile(jsonFilePath, sym = true)
      # get the hash define in the jsonFilePath.json file
    # configuration are define by symbol (ex: configurations[:key]) except if sym is false

    if !File.exist?(jsonFilePath)
        puts "no file : #{jsonFilePath}"
        return nil
      end
      jsonConfigurationFile = File.read(jsonFilePath)
      
      begin
        hash = JSON.parse(jsonConfigurationFile,:symbolize_names => sym)
      rescue JSON::ParserError
          return nil
      end
      return hash
  end  

app/helpers/panneaus_helper.rb
module PanneausHelper
end

app/views/panneaus/_form.html.erb
  <%= form_for(panneau) do |f| %>
    <% if panneau.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(panneau.errors.count, "error") %> prohibited this panneau from being saved:</h2>

        <ul>
        <% panneau.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.switch :is_ok, label: "Bon état ?" %>
    </div>

    <div class="field">
      <%= f.label :ville %>
      <!--<%= f.text_field :name %>-->
      <select name="panneau[ville]">
        <% @villes.each do |ville|%>
          <% puts panneau.ville%>
          <% if ville == panneau.ville%>
            <option value="<%=ville%>" selected><%=ville%></option>
          <%else%>
            <option value="<%=ville%>" ><%=ville%></option>
          <%end%>
        <% end%>
      </select>
    </div>

    <div class="field">
      <%= f.label :lat %>
      <%= f.text_field :lat%>
    </div>

    <div class="field">
      <%= f.label :long %>
      <%= f.text_field :long %>
    </div>

    <div class="actions">
      <%= f.submit class: "button" %>
    </div>
  <% end %>

app/views/panneaus/edit.html.erb
<h1>Editing Panneau</h1>

<%= render 'form', panneau: @panneau %>

<%= link_to 'Show', @panneau %> |
<%= link_to 'Back', panneaus_path %>

app/views/panneaus/edit_state.html.erb
<h1>Editing Panneau</h1>

  <%= form_for(@panneau) do |f| %>
    <% if @panneau.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(panneau.errors.count, "error") %> prohibited this panneau from being saved:</h2>

        <ul>
        <% panneau.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, disabled:true %>
    </div>

    <div class="field">
        <%= f.switch :is_ok, label: "Bon état ?" %>
    </div>

    <div class="field">
      <%= f.label :ville %>
      <%= f.text_field :ville, disabled:true %>
    </div>

    <div class="field">
      <%= f.label :lat %>
      <%= f.text_field :lat, disabled:true%>
    </div>

    <div class="field">
      <%= f.label :long %>
      <%= f.text_field :long, disabled:true %>
    </div>

    <div class="actions">
      <%= f.submit class: "button" %>
    </div>
  <% end %>

<%= link_to 'Show', @panneau %> |
<%= link_to 'Back', panneaus_path %>

app/views/panneaus/google_map.html.erb
 
  <h1 id="closest_panneau"> Recharger en cas si rien ne se passe au bout de 10 secondes</h1>
  <div id="cmd" class="row button-group">
      <div class="button small-4 large-4 columns" onclick="change_panneaus_info_google_map({'is_ok':true});">Bon état</div>
      <div class="button small-4 large-4 columns"onclick="change_panneaus_info_google_map({'is_ok':false});">A recoller</div>
  </div>

  <!-- load giff-->
  <div class= "modal"></div>

  <div class="row">
    <div style="max-height: 1200px; height: 500px;" class="small-12 large-12 columns" id="mapdiv"></div>

    <hr>
    <div id="show_circo" class="button" onclick="show_circo();" >affiche contour de circonscriptions</div>
  </div>



  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzV04B77KxUM3NcLsXVA9U_2D7v1BwKMA"></script>
  <script type="text/javascript">

  var gm_marker = [];

  $( document ).ready(function() {
      
      if (window.location.protocol == "http:"){
        $("H1").html("!! Passez en HTTPS:// dans la barre d'adresse !!!");
      }
      loadGiff(true);
      initGoogleMap();

  });


  </script>

app/views/panneaus/index.html.erb
<table>
  <% if @editable %>
  <tr>

    <td colspan="3">

        <%= link_to new_panneau_path(ville: params[:ville]), class: "button" do %>
              nouveau panneau
        <%end%>
    </td>
  </tr>
  <%end%>
  <%@panneaus.each do |panneau|%>
    <tr>
      <td>
          <% if @editable %>
            <%= panneau[:name] %>
            <%= link_to panneau_path(:id => panneau.id), data: { confirm: 'supprimer définitivement' }, class: 'btn btn-danger', method: :delete do %>
              supprimer
            <% end %>
          <%else%>
            <%= panneau[:name] %>
          <% end %>
      </td>
      <td>  
        <% if panneau.updated_at %>
          <%= panneau.updated_at %>
        <% else %>
          Jamais inspecté
        <% end%>
      </td>
      <td>
          <% if panneau[:is_ok] %> 
            <%= link_to edit_panneau_path(panneau), class: "warning button" do %>
              <i class="gen-enclosed foundicon-checkmark"></i><p id=<%=panneau.id%> >Bon état</p>
            <%end%>
          <%else%>
            <%= link_to edit_panneau_path(panneau), class: "alert button" do %>
              <i class="social foundicon-thumb-down panneau_pourri"></i><p id=<%=panneau.id%>>A recoller</p>
            <%end%>
          <%end%>
      </td>
    </tr>
  <%end%>
</table>

app/views/panneaus/new.html.erb
<h1>New Panneau</h1>

<%= render 'form', panneau: @panneau %>

<%= link_to 'Back', panneaus_path %>

app/views/panneaus/open_street_map.html.erb
  <h1 id="closest_panneau"> Recharger en cas si rien ne se passe au bout de 10 secondes</h1>

  <div class="row button-group">
      <div class="button small-4 large-4 columns" onclick="change_panneaus_info({'is_ok':true});">Bon état</div>
      <div class="button small-4 large-4 columns" onclick="change_panneaus_info({'is_ok':false});">A recoller</div>
  </div>

  <!-- load giff-->
  <div class= "modal"></div>

  <div class="row">
    <div style="max-height: 800px; height: 300px;" class="small-12 large-12 columns" id="mapdiv"></div>
  </div>

  <script type="text/javascript">
    $( document ).ready(function() {
        if (window.location.protocol == "http:"){
          $("H1").html("!! Passez en HTTPS:// dans la barre d'adresse !!!");
        }
        loadGiff(true);
        document.addEventListener("deviceready",init_geoloc(),false);

    });
  </script>

app/views/panneaus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @panneau.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @panneau.long %>
</p>

<p>
  <strong>Name:</strong>
  <%= @panneau.name %>
</p>

<p>
  <strong>Is ok:</strong>
  <%= @panneau.is_ok %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @panneau.ville %>
</p>

<%= link_to 'Edit', edit_panneau_path(@panneau) %> |
<%= link_to 'Back', panneaus_path %>